name: first workflow
on:
  push:
    branches:
      - master
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome massage
        run: echo "welcome to my first workflow"
